[package]
name = "rust_lib_lnu_elytra"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]
[dependencies]
flutter_rust_bridge = "=2.13.0-beta.5"
lnu-elytra = { path = "core", features = [
    "__flutter",
    "reqwest_cookie_store",
    "tracing",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", default-features = false, features = [
    "registry",
    "std",
] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22.4"
ndk-context = "0.1.1"
rustls-platform-verifier = "0.7.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

